const {
  MessageEmbed,
  MessageActionRow,
  MessageButton,
  Modal,
  TextInputComponent,
  MessageAttachment
} = require('discord.js');
const { generateCharacterStory, patchHighlightedSentences } = require('../ai');
const { isHumanText } = require('../utils/zerogpt');
const config = require('../config.json');
const path   = require('path');
const os     = require('os');
const fs     = require('fs');

const BUTTON_ID = config.csButtonId;
const MODAL_ID  = config.csModalId;

// Safety cap — batas percobaan maksimal sebelum menyerah
const MAX_ZEROGPT_RETRY = 15;

// ─── Capitalize every word of a string ────────────────────────────────────────
function capitalizeWords(str) {
  return str
    .split(' ')
    .map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join(' ');
}

/**
 * Ubah kata ulang yang masih dipisah spasi menjadi bentuk bertanda hubung.
 * Contoh: "hari hari" → "hari-hari", "Siang   siang" → "Siang-siang".
 *
 * Ini dijalankan setelah teks lolos ZeroGPT, sehingga tahap deteksi tetap
 * memeriksa teks hasil generasi/patch dan tidak terpengaruh oleh formatting
 * akhir ini.
 */
function hyphenateReduplicatedWords(text) {
  return String(text || '').replace(
    /\b([\p{L}]+)\s+([\p{L}]+)\b/giu,
    (match, first, second) => {
      if (first.localeCompare(second, undefined, { sensitivity: 'base' }) !== 0) {
        return match;
      }
      return `${first}-${second.toLowerCase()}`;
    }
  );
}

// ─── %cr-cs command ───────────────────────────────────────────────────────────

async function handleCrCsCommand(message) {
  const embed = new MessageEmbed()
    .setColor(config.embedColor)
    .setTitle('📝 Character Story Generator')
    .setDescription(
      '**Tekan tombol di bawah untuk membuat Character Story kamu!**\n\n' +
      '> Isi form dengan data karakter IC kamu.\n' +
      '> AI akan otomatis membuat CS berkualitas tinggi.\n' +
      '> Hasil dikirim dalam format `.txt` siap pakai.\n' +
      '> CS **dijamin** lolos 0% ZeroGPT sebelum dikirim.'
    )
    .addField('✅ Fitur', [
      '• Gaya penulisan ambigu & natural',
      '• Analisis realtime contoh ambiguitas',
      '• Generasi instant — tidak bertele-tele',
      '• Wajib lolos 0% ZeroGPT sebelum dikirim',
      '• Format file `.txt` langsung pakai'
    ].join('\n'))
    .setFooter({ text: 'Character Story • Powered by Dott' })
    .setTimestamp();

  const row = new MessageActionRow().addComponents(
    new MessageButton()
      .setCustomId(BUTTON_ID)
      .setLabel('✍️ Create CS')
      .setStyle('PRIMARY')
      .setEmoji('📋')
  );

  await message.channel.send({ embeds: [embed], components: [row] });
}

// ─── Button click → show modal ────────────────────────────────────────────────

async function handleCreateCsButton(interaction) {
  const modal = new Modal()
    .setCustomId(MODAL_ID)
    .setTitle('📋 Form Character Story');

  modal.addComponents(
    new MessageActionRow().addComponents(
      new TextInputComponent()
        .setCustomId('nama_ic')
        .setLabel('Nama Character IC')
        .setStyle('SHORT')
        .setPlaceholder('Contoh: Tomas Ferrant')
        .setRequired(true)
        .setMaxLength(50)
    ),
    new MessageActionRow().addComponents(
      new TextInputComponent()
        .setCustomId('ttl')
        .setLabel('Tempat, Tanggal Lahir')
        .setStyle('SHORT')
        .setPlaceholder('Contoh: Los Santos, 12 Januari 2000')
        .setRequired(true)
        .setMaxLength(100)
    ),
    new MessageActionRow().addComponents(
      new TextInputComponent()
        .setCustomId('pekerjaan')
        .setLabel('Pekerjaan')
        .setStyle('SHORT')
        .setPlaceholder('Contoh: Petani, Mekanik, Pedagang')
        .setRequired(true)
        .setMaxLength(80)
    ),
    new MessageActionRow().addComponents(
      new TextInputComponent()
        .setCustomId('jumlah_paragraf')
        .setLabel('Jumlah Paragraf (1-4)')
        .setStyle('SHORT')
        .setPlaceholder('Contoh: 4')
        .setRequired(true)
        .setMaxLength(1)
    )
  );

  await interaction.showModal(modal);
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function parseParagrafField(raw) {
  const numberMatch = raw.trim().match(/\d+/);
  const jumlah = numberMatch ? Math.min(4, Math.max(1, parseInt(numberMatch[0]))) : 4;
  return { jumlahParagraf: jumlah };
}

function parseTTL(ttlRaw) {
  const parts = ttlRaw.split(',').map(s => s.trim());
  return parts.length >= 2
    ? { kota: parts[0], tanggal: parts.slice(1).join(',').trim() }
    : { kota: ttlRaw, tanggal: ttlRaw };
}

function buildTxtContent(nama, ttlRaw, pekerjaan, csText) {
  return [
    'CHARACTER STORY',
    '═══════════════════════════════════════',
    `Nama     : ${nama}`,
    `TTL      : ${ttlRaw}`,
    `Pekerjaan: ${pekerjaan}`,
    '═══════════════════════════════════════',
    '',
    csText,
    '',
    '═══════════════════════════════════════',
    'Generated by Character Story Bot',
    'ZeroGPT  : ✅ 0% AI — Lolos 100% Human'
  ].join('\n');
}

function statusEmbed(color, title, description) {
  return new MessageEmbed()
    .setColor(color)
    .setTitle(title)
    .setDescription(description)
    .setTimestamp();
}

// ─── Modal submit → generate → ZeroGPT loop wajib 0% → send .txt ─────────────

async function handleCsModalSubmit(interaction) {
  await interaction.deferReply({ ephemeral: true });

  const nama          = interaction.fields.getTextInputValue('nama_ic').trim();
  const ttlRaw        = interaction.fields.getTextInputValue('ttl').trim();
  const pekerjaanRaw  = interaction.fields.getTextInputValue('pekerjaan').trim();
  const paragrafRaw   = interaction.fields.getTextInputValue('jumlah_paragraf').trim();

  // Profesi selalu diawali kapital pada setiap kata
  const pekerjaan = capitalizeWords(pekerjaanRaw);

  const { kota, tanggal }       = parseTTL(ttlRaw);
  const { jumlahParagraf }      = parseParagrafField(paragrafRaw);
  const formData = { nama, ttl: tanggal, kota, pekerjaan, jumlahParagraf };

  // ── Step 1: Generate CS ───────────────────────────────────────────────────
  await interaction.editReply({
    embeds: [statusEmbed(config.embedColor, '⏳ Membuat Character Story...',
      `**Karakter:** ${nama} | **TTL:** ${ttlRaw}\n` +
      `**Pekerjaan:** ${pekerjaan} | **Paragraf:** ${jumlahParagraf}\n\n` +
      `> 🤖 AI sedang menulis CS dengan analisis contoh ambiguitas...`
    )]
  });

  let csText;
  try {
    csText = await generateCharacterStory(formData);
  } catch (err) {
    console.error('[CS] Generate error:', err.message);
    return interaction.editReply({
      embeds: [statusEmbed(config.embedColorError, '❌ Gagal Generate CS',
        `Error dari AI: \`${err.message}\`\nCoba lagi beberapa saat.`
      )]
    });
  }

  // ── Step 2: ZeroGPT loop — WAJIB 0%, tidak kirim sebelum lolos ────────────
  let zerogptResult;
  let attempt = 0;

  while (true) {
    attempt++;

    await interaction.editReply({
      embeds: [statusEmbed(config.embedColor, '🔍 Verifikasi ZeroGPT...',
        `> Cek ke-**${attempt}** — Memastikan teks lolos 0% AI sebelum dikirim...`
      )]
    });

    zerogptResult = await isHumanText(csText);

    // ── API tidak tersedia — JANGAN kirim, beritahu user ──────────────────
    if (zerogptResult.skipped) {
      console.warn('[ZeroGPT] API tidak tersedia — menghentikan proses.');
      return interaction.editReply({
        embeds: [statusEmbed(config.embedColorError, '❌ ZeroGPT Tidak Tersedia',
          `**Karakter:** ${nama}\n\n` +
          `> ZeroGPT API tidak dapat dihubungi saat ini.\n` +
          `> CS **tidak dikirim** karena belum terverifikasi.\n\n` +
          `Coba jalankan \`%cr-cs\` lagi beberapa saat kemudian.`
        )]
      });
    }

    const score = zerogptResult.aiScore;
    console.log(`[ZeroGPT] Attempt ${attempt}: ${score}% AI | Highlighted: ${zerogptResult.highlightedSentences.length} kalimat`);

    // ✅ 0% — lolos, keluar loop dan kirim
    if (score === 0) break;

    // Safety cap — sudah terlalu banyak percobaan, JANGAN kirim
    if (attempt >= MAX_ZEROGPT_RETRY) {
      console.warn(`[ZeroGPT] Safety cap ${MAX_ZEROGPT_RETRY} tercapai, ${score}% masih terdeteksi.`);
      return interaction.editReply({
        embeds: [statusEmbed(config.embedColorError, '❌ Gagal Lolos ZeroGPT',
          `**Karakter:** ${nama}\n\n` +
          `Setelah **${attempt} percobaan**, CS masih terdeteksi **${score}% AI** oleh ZeroGPT.\n\n` +
          `> CS **tidak dikirim** karena belum lolos verifikasi.\n` +
          `> Coba jalankan \`%cr-cs\` lagi untuk hasil yang lebih baik.`
        )]
      });
    }

    if (score === 100) {
      // ── Full Rewrite: 100% AI → Buat ulang seluruh teks ─────────────────
      await interaction.editReply({
        embeds: [statusEmbed('#FEE75C',
          `🔄 ZeroGPT: ${score}% AI — Menulis Ulang... (${attempt}/${MAX_ZEROGPT_RETRY})`,
          `> Seluruh teks 100% terdeteksi AI.\n> Membuat ulang Character Story dari awal...`
        )]
      });

      try {
        csText = await generateCharacterStory(formData);
      } catch (err) {
        console.error('[CS] Full rewrite error:', err.message);
        return interaction.editReply({
          embeds: [statusEmbed(config.embedColorError, '❌ Gagal Menulis Ulang CS',
            `Error dari AI: \`${err.message}\`\nCoba lagi beberapa saat.`
          )]
        });
      }

    } else {
      // ── Patch Highlight: >0% & <100% → Ubah HANYA kalimat kuning ─────────
      const highlighted = zerogptResult.highlightedSentences;
      const totalKalimat = csText.split(/(?<=[.!?])\s+/).filter(s => s.trim().length > 5).length;
      const simpanCount  = totalKalimat - highlighted.length;

      await interaction.editReply({
        embeds: [statusEmbed('#FEE75C',
          `✏️ ZeroGPT: ${score}% AI — Patch ${highlighted.length} Kalimat... (${attempt}/${MAX_ZEROGPT_RETRY})`,
          `> 💾 **${simpanCount > 0 ? simpanCount : 0} kalimat** bukan highlight → **disimpan persis aslinya**\n` +
          `> ✏️ **${highlighted.length} kalimat** highlight kuning → dikirim ke AI untuk diperbaiki\n` +
          `> 🔗 Hasil kalimat baru disisipkan kembali ke posisi aslinya`
        )]
      });

      try {
        csText = await patchHighlightedSentences(csText, highlighted);
      } catch (err) {
        console.error('[CS] Patch error:', err.message);
        // Fallback ke full rewrite jika patch gagal
        try {
          csText = await generateCharacterStory(formData);
        } catch (err2) {
          console.error('[CS] Fallback rewrite error:', err2.message);
          return interaction.editReply({
            embeds: [statusEmbed(config.embedColorError, '❌ Gagal Patch CS',
              `Error dari AI: \`${err2.message}\`\nCoba lagi beberapa saat.`
            )]
          });
        }
      }
    }
  }

  // ── Step 3: 0% lolos — Tulis & kirim file .txt ────────────────────────────
  // Formatting kata ulang dilakukan setelah ZeroGPT lolos agar tidak terdeteksi 
  // sebagai pola AI saat dicek ZeroGPT.
  csText = hyphenateReduplicatedWords(csText);

  const fileName = `Character Story - ${nama}.txt`;
  const tmpPath  = path.join(os.tmpdir(), fileName);

  fs.writeFileSync(tmpPath, buildTxtContent(nama, ttlRaw, pekerjaan, csText), 'utf-8');
  const attachment = new MessageAttachment(tmpPath, fileName);

  await interaction.editReply({
    embeds: [
      new MessageEmbed()
        .setColor(config.embedColorSuccess)
        .setTitle('✅ Character Story Selesai!')
        .setDescription(
          `**Karakter:** ${nama}\n` +
          `**TTL:** ${ttlRaw}\n` +
          `**Pekerjaan:** ${pekerjaan}\n` +
          `**Paragraf:** ${jumlahParagraf}\n\n` +
          `**ZeroGPT:** ✅ 0% AI — Lolos! Teks 100% terdeteksi Human`
        )
        .setFooter({ text: 'File .txt terlampir di bawah' })
        .setTimestamp()
    ],
    files: [attachment]
  });

  try { fs.unlinkSync(tmpPath); } catch (_) {}
}

module.exports = {
  handleCrCsCommand,
  handleCreateCsButton,
  handleCsModalSubmit,
  hyphenateReduplicatedWords,
  BUTTON_ID,
  MODAL_ID
};
