const {
  MessageEmbed,
  MessageActionRow,
  MessageButton,
  Modal,
  TextInputComponent,
  MessageAttachment
} = require('discord.js');
const { generateCharacterStory } = require('../ai');
const { isHumanText } = require('../utils/zerogpt');
const config = require('../config.json');
const path = require('path');
const os = require('os');
const fs = require('fs');

const BUTTON_ID = config.csButtonId;
const MODAL_ID = config.csModalId;

// Maximum retries for ZeroGPT — keeps going until 0% or limit hit
const MAX_ZEROGPT_RETRY = 10;

// ─── %cr-cs command ───────────────────────────────────────────────────────────

async function handleCrCsCommand(message) {
  const embed = new MessageEmbed()
    .setColor(config.embedColor)
    .setTitle('📝 Character Story Generator')
    .setDescription(
      '**Tekan tombol di bawah untuk membuat Character Story kamu!**\n\n' +
      '> Isi form dengan data karakter IC kamu.\n' +
      '> AI akan otomatis membuat CS berkualitas tinggi.\n' +
      '> Hasil dikirim dalam format `.txt` siap pakai.'
    )
    .addField('✅ Fitur', [
      '• Gaya penulisan ambigu & natural',
      '• Ditulis oleh Claude Sonnet',
      '• Lolos uji ZeroGPT',
      '• Format file `.txt` langsung pakai'
    ].join('\n'))
    .setFooter({ text: 'Character Story • Powered by Dott' })
    .setTimestamp();

  const row = new MessageActionRow().addComponents(
    new MessageButton()
      .setCustomId(BUTTON_ID)
      .setLabel('✍️ Create CS')
      .setStyle('PRIMARY')
      .setEmoji('📋')
  );

  await message.channel.send({ embeds: [embed], components: [row] });
}

// ─── Button click → show modal ────────────────────────────────────────────────

async function handleCreateCsButton(interaction) {
  const modal = new Modal()
    .setCustomId(MODAL_ID)
    .setTitle('📋 Form Character Story');

  modal.addComponents(
    new MessageActionRow().addComponents(
      new TextInputComponent()
        .setCustomId('nama_ic')
        .setLabel('Nama Character IC')
        .setStyle('SHORT')
        .setPlaceholder('Contoh: Tomas Ferrant')
        .setRequired(true)
        .setMaxLength(50)
    ),
    new MessageActionRow().addComponents(
      new TextInputComponent()
        .setCustomId('ttl')
        .setLabel('Tempat, Tanggal Lahir')
        .setStyle('SHORT')
        .setPlaceholder('Contoh: Los Santos, 12 Januari 2000')
        .setRequired(true)
        .setMaxLength(100)
    ),
    new MessageActionRow().addComponents(
      new TextInputComponent()
        .setCustomId('pekerjaan')
        .setLabel('Pekerjaan')
        .setStyle('SHORT')
        .setPlaceholder('Contoh: Petani, Mekanik, Pedagang')
        .setRequired(true)
        .setMaxLength(80)
    ),
    new MessageActionRow().addComponents(
      new TextInputComponent()
        .setCustomId('jumlah_paragraf')
        .setLabel('Jumlah Paragraf (1-4) & Status')
        .setStyle('SHORT')
        .setPlaceholder('Contoh: 4, sukses  ATAU  3, tidak sukses')
        .setRequired(true)
        .setMaxLength(30)
    )
  );

  await interaction.showModal(modal);
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

/** Parse "4, sukses" | "3, tidak sukses" */
function parseParagrafField(raw) {
  const cleaned = raw.toLowerCase().trim();
  const numberMatch = cleaned.match(/\d+/);
  const jumlah = numberMatch ? Math.min(4, Math.max(1, parseInt(numberMatch[0]))) : 4;
  const sukses = cleaned.includes('tidak') ? 'tidak sukses' : 'sukses';
  return { jumlahParagraf: jumlah, sukses };
}

/** Parse "Los Santos, 12 Januari 2000" → { kota, tanggal } */
function parseTTL(ttlRaw) {
  const parts = ttlRaw.split(',').map(s => s.trim());
  return parts.length >= 2
    ? { kota: parts[0], tanggal: parts.slice(1).join(',').trim() }
    : { kota: ttlRaw, tanggal: ttlRaw };
}

/** Build the plain-text .txt file content */
function buildTxtContent(nama, ttlRaw, pekerjaan, sukses, csText, zerogptResult) {
  const zerogptLine = zerogptResult.skipped
    ? 'ZeroGPT  : Tidak dicek (API unavailable)'
    : `ZeroGPT  : ${zerogptResult.aiScore}% AI | ${zerogptResult.isHuman}% Human`;

  return [
    'CHARACTER STORY',
    '═══════════════════════════════════════',
    `Nama     : ${nama}`,
    `TTL      : ${ttlRaw}`,
    `Pekerjaan: ${pekerjaan}`,
    `Status   : ${sukses}`,
    '═══════════════════════════════════════',
    '',
    csText,
    '',
    '═══════════════════════════════════════',
    'Generated by Character Story Bot',
    zerogptLine
  ].join('\n');
}

// ─── Modal submit → generate → ZeroGPT loop → send .txt ──────────────────────

async function handleCsModalSubmit(interaction) {
  await interaction.deferReply({ ephemeral: true });

  const nama       = interaction.fields.getTextInputValue('nama_ic').trim();
  const ttlRaw     = interaction.fields.getTextInputValue('ttl').trim();
  const pekerjaan  = interaction.fields.getTextInputValue('pekerjaan').trim();
  const paragrafRaw = interaction.fields.getTextInputValue('jumlah_paragraf').trim();

  const { kota, tanggal }         = parseTTL(ttlRaw);
  const { jumlahParagraf, sukses } = parseParagrafField(paragrafRaw);

  const formData = { nama, ttl: tanggal, kota, pekerjaan, sukses, jumlahParagraf };

  // ── Step 1: Generate ────────────────────────────────────────────────────────
  await interaction.editReply({
    embeds: [statusEmbed(config.embedColor, '⏳ Membuat Character Story...',
      `**Karakter:** ${nama} | **TTL:** ${ttlRaw}\n` +
      `**Pekerjaan:** ${pekerjaan} | **Paragraf:** ${jumlahParagraf} | **Status:** ${sukses}\n\n` +
      `> 🤖 Claude Sonnet sedang menulis CS kamu...`
    )]
  });

  let csText;
  try {
    csText = await generateCharacterStory(formData, 1);
  } catch (err) {
    console.error('[CS] Generate error:', err.message);
    return interaction.editReply({
      embeds: [statusEmbed(config.embedColorError, '❌ Gagal Generate CS',
        `Error dari AI: \`${err.message}\`\nCoba lagi beberapa saat.`
      )]
    });
  }

  // ── Step 2: ZeroGPT retry loop — target exactly 0% ─────────────────────────
  let zerogptResult = { passed: false, aiScore: 100, isHuman: 0, skipped: false };
  let attempt = 1;

  while (attempt <= MAX_ZEROGPT_RETRY) {
    await interaction.editReply({
      embeds: [statusEmbed(config.embedColor, '🔍 Mengecek ZeroGPT...',
        `> Attempt **${attempt}/${MAX_ZEROGPT_RETRY}** — Mengecek apakah teks lolos 0% AI...`
      )]
    });

    zerogptResult = await isHumanText(csText);

    // API unavailable — skip gracefully
    if (zerogptResult.skipped) {
      console.warn('[ZeroGPT] API tidak tersedia — skip.');
      break;
    }

    console.log(`[ZeroGPT] Attempt ${attempt}: ${zerogptResult.aiScore}% AI`);

    // 0% achieved — done!
    if (zerogptResult.aiScore === 0) break;

    // Not 0% — regenerate with escalating prompt
    if (attempt < MAX_ZEROGPT_RETRY) {
      await interaction.editReply({
        embeds: [statusEmbed('#FEE75C',
          `⚠️ ZeroGPT: ${zerogptResult.aiScore}% AI — Regenerating... (${attempt}/${MAX_ZEROGPT_RETRY})`,
          `> Teks terdeteksi AI. Menulis ulang dengan gaya lebih human...`
        )]
      });

      try {
        // Pass attempt+1 so escalated system prompt is used
        csText = await generateCharacterStory(formData, attempt + 1);
      } catch (err) {
        console.error('[CS] Regenerate error:', err.message);
        break;
      }
    }

    attempt++;
  }

  // ── Step 3: Write .txt (clean, no markdown) ─────────────────────────────────
  const fileName = `Character Story - ${nama}.txt`;
  const tmpPath  = path.join(os.tmpdir(), fileName);

  fs.writeFileSync(tmpPath, buildTxtContent(nama, ttlRaw, pekerjaan, sukses, csText, zerogptResult), 'utf-8');

  const attachment = new MessageAttachment(tmpPath, fileName);

  // ── Step 4: Send result ─────────────────────────────────────────────────────
  const passed = zerogptResult.skipped || zerogptResult.aiScore === 0;
  const resultColor = passed ? config.embedColorSuccess : '#FEE75C';

  let zerogptStatus;
  if (zerogptResult.skipped) {
    zerogptStatus = '⚠️ Tidak dicek (ZeroGPT API unavailable)';
  } else if (zerogptResult.aiScore === 0) {
    zerogptStatus = `✅ 0% AI — Lolos! Teks 100% terdeteksi Human`;
  } else {
    zerogptStatus = `⚠️ ${zerogptResult.aiScore}% AI setelah ${attempt} percobaan — dikirim tetap`;
  }

  await interaction.editReply({
    embeds: [
      new MessageEmbed()
        .setColor(resultColor)
        .setTitle('✅ Character Story Selesai!')
        .setDescription(
          `**Karakter:** ${nama}\n` +
          `**TTL:** ${ttlRaw}\n` +
          `**Pekerjaan:** ${pekerjaan}\n` +
          `**Paragraf:** ${jumlahParagraf} | **Status:** ${sukses}\n\n` +
          `**ZeroGPT:** ${zerogptStatus}`
        )
        .setFooter({ text: 'File .txt terlampir di bawah' })
        .setTimestamp()
    ],
    files: [attachment]
  });

  // Cleanup
  try { fs.unlinkSync(tmpPath); } catch (_) {}
}

// ─── Shared embed builder ─────────────────────────────────────────────────────

function statusEmbed(color, title, description) {
  return new MessageEmbed()
    .setColor(color)
    .setTitle(title)
    .setDescription(description)
    .setTimestamp();
}

module.exports = { handleCrCsCommand, handleCreateCsButton, handleCsModalSubmit, BUTTON_ID, MODAL_ID };
